# Generated by Django 5.1.7 on 2025-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_accounts_aadhar_alter_accounts_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.EmailField(default='dhanushaerolla02@gmail.com', max_length=254),
        ),
    ]
