# Generated by Django 5.1.7 on 2025-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_accounts_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='Aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='pan',
            field=models.CharField(max_length=10),
        ),
    ]
